### ISSUE TITLE
Accessing certain functions give an exception

### ISSUE THREAD

**Issue by MZ2106644** [janschneiderou/PT2023#2]
I added your latest changes to my forked project. The issue that arises now is that when certain functions within the application are accessed, an exception occurs. The functions of the application that cause that particular exception are "Work with Script", "Memorise Presentation" and "Practice Presentation". I already tried it with and without the added slides, no difference there. What I also tried was to clone your project and try the same functions to see if that would make a difference but it gave me the same exception errors.

Here is a screenshot of the exception error message:
![Exception](https://github.com/janschneiderou/PT2023/assets/102732823/fd5e488d-9ac9-4af2-9f89-14de75a242c8)
`System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PT2023.utilObjects.SlideHandler.getStartIndexes() in C:\Users\Marlon\source\repos\PT2023\PT2023\utilObjects\SlideHandler.cs:line 102
   at PT2023.utilObjects.SlideHandler.init() in C:\Users\Marlon\source\repos\PT2023\PT2023\utilObjects\SlideHandler.cs:line 26
   at PT2023.WorkingWithScript.getSlides() in C:\Users\Marlon\source\repos\PT2023\PT2023\WorkingWithScript.xaml.cs:line 332
   at PT2023.WorkingWithScript..ctor() in C:\Users\Marlon\source\repos\PT2023\PT2023\WorkingWithScript.xaml.cs:line 38
   at PT2023.WelcomePage.Button_add_Script_Click(Object sender, RoutedEventArgs e) in C:\Users\Marlon\source\repos\PT2023\PT2023\WelcomePage.xaml.cs:line 317
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at PT2023.App.Main()
`

I hope you can reproduce the issue and resolve it.

**Comment by janschneiderou** [comment]
It seems that I fixed that error, and it will not appear if there are no selected slides. It is not explained anywhere at the moment but to select slides, you first need in power point to save them as .png . The you select the folder where the .png files are stored. 
After that it should work

**Comment by MZ2106644** [comment]
Okay, it works again. Thank you for your time and effort.
